
services:
  server:
    build:
      context: ./server
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
      - ./server/src:/usr/app/src
  #   depends_on:
  #     - db
      
  # db:
  #   image: mongodb/mongodb-community-server:6.0-ubi8
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=user
  #     - MONGO_INITDB_ROOT_PASSWORD=pass
  #   volumes:
  #     - type: bind
  #       source: ./data
  #       target: /data/db
