services:
  server:
    build:
      context: ./
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
      - ./src:/usr/app/src
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    user: root
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: {}
