services:
    server:
        build:
            context: ./
        environment:
            NODE_ENV: ${NODE_ENV} # development or production
            MONGODB_USERNAME: ${MONGODB_USERNAME}
            MONGODB_PASSWORD: ${MONGODB_PASSWORD}
            MONGODB_DATABASE: ${MONGODB_DATABASE}
        ports:
            - 4000:4000 # for server
            - 8000:8000 # for devtools
        volumes:
            - ./src:/usr/app/src
        depends_on:
            - database

    database:
        image: mongo
        user: root
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
        ports:
            - 27017:27017
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data: {}
